# Generated by Django 4.1.6 on 2023-07-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PostID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
    ]
