# Generated by Django 4.1.6 on 2023-07-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_post_is_private_post_owner_alter_like_post_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='post',
        #     name='owner',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cms_app.user'),
        # ),
    ]
